<?php
$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude([
        'bootstrap/cache',
        'node_modules',
        'public',
        'storage',
        'vendor',
    ])
    ->notName([
        '*.blade.php',
        '_ide_helper.php',
        '_ide_helper_actions.php',
        '_ide_helper_models.php',
        '.phpstorm.meta.php',
    ])
    ->name('*.php');
return (new PhpCsFixer\Config())
    ->setFinder($finder)
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR12' => true,
        'array_indentation' => true,
        'array_syntax' => ['syntax' => 'short'],
        'list_syntax' => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_whitespace_before_comma_in_array' => true,
        'trim_array_spaces' => true,
        'whitespace_after_comma_in_array' => ['ensure_single_space' => true],
        'no_spaces_around_offset' => true,
        'trailing_comma_in_multiline' => [
            'elements' => [
                'arguments',
                'arrays',
                'match',
                'parameters',
            ],
        ],
        'no_trailing_comma_in_singleline' => true,
        'single_quote' => true,
        'explicit_string_variable' => true,
        'simple_to_complex_string_variable' => true,
        'explicit_indirect_variable' => true,
        'concat_space' => ['spacing' => 'one'],
        'binary_operator_spaces' => true,
        'unary_operator_spaces' => true,
        'not_operator_with_successor_space' => true,
        'object_operator_without_whitespace' => true,
        'cast_spaces' => true,
        'lowercase_cast' => true,
        'no_short_bool_cast' => true,
        'no_unset_cast' => true,
        'types_spaces' => true,
        'type_declaration_spaces' => true,
        'single_space_around_construct' => true,
        'operator_linebreak' => ['only_booleans' => true],
        'standardize_not_equals' => true,
        'no_multiple_statements_per_line' => true,
        'semicolon_after_instruction' => true,
        'space_after_semicolon' => ['remove_in_empty_for_expressions' => true],
        'no_singleline_whitespace_before_semicolons' => true,
        'multiline_whitespace_before_semicolons' => true,
        'no_empty_statement' => true,
        'statement_indentation' => true,
        'method_chaining_indentation' => true,
        'control_structure_braces' => true,
        'control_structure_continuation_position' => true,
        'braces_position' => ['functions_opening_brace' => 'same_line'],
        'single_line_empty_body' => true,
        'no_superfluous_elseif' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'ordered_imports' => ['sort_algorithm' => 'alpha'],
        'single_import_per_statement' => false,
        'group_import' => true,
        'global_namespace_import' => true,
        'no_unused_imports' => true,
        'no_leading_namespace_whitespace' => true,
        'clean_namespace' => true,
        'fully_qualified_strict_types' => true,
        'class_reference_name_casing' => true,
        'magic_constant_casing' => true,
        'magic_method_casing' => true,
        'native_function_casing' => true,
        'native_type_declaration_casing' => true,
        'echo_tag_syntax' => ['format' => 'short'],
        'no_mixed_echo_print' => true,
        'new_with_parentheses' => ['anonymous_class' => false],
        'include' => true,
        'linebreak_after_opening_tag' => true,
        'single_class_element_per_statement' => true,
        'no_extra_blank_lines' => [
            'tokens' => [
                'curly_brace_block',
                'extra',
                'parenthesis_brace_block',
                'square_brace_block',
                'throw',
                'use',
            ],
        ],
        'class_attributes_separation' => [
            'elements' => [
                'trait_import' => 'one',
                'case' => 'none',
                'const' => 'one',
                'property' => 'one',
                'method' => 'one',
            ],
        ],
        'ordered_class_elements' => [
            'order' => [
                'use_trait',
                'case',
                'constant_public',
                'constant_protected',
                'constant_private',
                'property_public',
                'property_protected',
                'property_private',
                'construct',
                'destruct',
                'magic',
                'phpunit',
                'method_public',
                'method_protected',
                'method_private',
            ],
        ],
        'declare_strict_types' => true,
        'nullable_type_declaration_for_default_null_value' => true,
        'no_null_property_initialization' => true,
        'blank_line_before_statement' => ['statements' => ['return']],
        'strict_comparison' => true,
        'strict_param' => true,
        'ternary_to_null_coalescing' => true,
        'assign_null_coalescing_to_coalesce_equal' => true,
        'single_line_comment_style' => ['comment_types' => ['hash']],
        'single_line_comment_spacing' => true,
        'align_multiline_comment' => ['comment_type' => 'phpdocs_like'],
        'multiline_comment_opening_closing' => true,
        'no_empty_comment' => true,
        'no_superfluous_phpdoc_tags' => [
            'allow_mixed' => true,
            'remove_inheritdoc' => false,
        ],
        'no_blank_lines_after_phpdoc' => true,
        'no_empty_phpdoc' => true,
        'phpdoc_align' => ['align' => 'left'],
        'phpdoc_indent' => true,
        'phpdoc_line_span' => true,
        'phpdoc_order' => true,
        'phpdoc_separation' => true,
        'phpdoc_trim' => true,
        'phpdoc_trim_consecutive_blank_line_separation' => true,
        'phpdoc_types' => true,
        'phpdoc_types_order' => [
            'null_adjustment' => 'always_last',
            'sort_algorithm' => 'none',
        ],
        'phpdoc_var_annotation_correct_order' => true,
        'phpdoc_var_without_name' => true,
    ])
    ->setIndent('    ')
    ->setLineEnding("\n");
